### ISSUE TITLE
Error: Unexpected error

### ISSUE THREAD

**Issue by vinoth2442** [lit/lit.dev#1027]
I encountered the following error on lit.dev:

> Unexpected error
> Error calling GitHub API GET /gists/c199e214fe9a6da75aced55b7edb4ed9 (HTTP status 403)

Stack trace:
```
Error: Error calling GitHub API GET /gists/c199e214fe9a6da75aced55b7edb4ed9 (HTTP status 403)
    at y (https://lit.dev/js/components/litdev-playground-page.js:17:396)
    at async T._loadGist (https://lit.dev/js/components/litdev-playground-page.js:72:4433)
    at async T._syncStateFromUrlHash (https://lit.dev/js/components/litdev-playground-page.js:72:5693)
```

URL: https://lit.dev/playground/#sample=examples%2Fmotion-hero&view-mode=code&gist=c199e214fe9a6da75aced55b7edb4ed9
Site version: `prod-73e0861`
Browser: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`

**Comment by augustjk** [comment]
Looks to have been a transient github error. Page is loading fine now.
